spring:
  application:
    name: GAE

  profiles:
    active: dev

logging:
  level:
    org.fh.gae: info
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] - [%t] - [%level] %c{40} - %m%n"


gae:
  instance-id: 1

  server:
    port: 9000
    host: 0.0.0.0

    # 用于处理长时间业务的worker线程池最大线程数;
    max-worker-thread: 10
    # NIO线程数, 默认为CPU核心数
    nio-thread: 4

  # 如果一个请求有多个广告位, 则会并发检索
  # 此配置控制用于执行此逻辑的线程池参数
  thread-pool:
    core-size: 4
    max-size: 8
    queue-size: 1000

  index:
    file:
      enable: true
      path: .
      name: mock-idx.txt
      incr-path: /Users/whf/projects/open/gae/src/main/resources/mock
      incr-name: gae.idx.incr
      incr-interval: 500

    kafka:
      enable: false
      addr: host:port
      topic: gae-idx
  dict:
    ip: data/ipdict.txt

  min-unit-amount: 10000